# Generated by Django 3.1.3 on 2021-01-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinicio',
            name='superficie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Superficie (locales u oficina)'),
        ),
    ]
