# Generated by Django 3.1.3 on 2021-02-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinicio',
            name='price',
            field=models.FloatField(verbose_name='Precio'),
        ),
    ]
