# Generated by Django 3.1.3 on 2021-01-12 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20210112_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inicio',
            old_name='ambientes',
            new_name='dormitorios',
        ),
    ]
