# Generated by Django 3.1.3 on 2021-02-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20210227_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinicio',
            name='moneda',
            field=models.CharField(choices=[('U$S', 'U$S'), ('$', '$')], default='$', max_length=100),
        ),
    ]
