# Generated by Django 3.1.3 on 2021-01-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20210121_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Inicio', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='postinicio',
            name='plantas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plantas'),
        ),
        migrations.AlterField(
            model_name='postinicio',
            name='superficie',
            field=models.IntegerField(blank=True, verbose_name='Superficie'),
        ),
    ]
