# Generated by Django 3.1.3 on 2021-01-13 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_auto_20210112_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inicio',
            old_name='price',
            new_name='precio',
        ),
    ]
