# Generated by Django 3.1.3 on 2021-01-14 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_auto_20210113_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inicio',
            old_name='dormitorios',
            new_name='ambientes',
        ),
    ]
