# Generated by Django 3.1.3 on 2021-01-12 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comprar', '0002_auto_20210112_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprarImagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Imagenes', verbose_name='Imagenes')),
                ('comprar', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Comprar.comprar')),
            ],
        ),
    ]
