# Generated by Django 3.1.3 on 2021-01-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comprar', '0003_comprarimagenes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprar',
            options={},
        ),
    ]
