# Generated by Django 3.1.3 on 2021-01-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comprar', '0004_auto_20210112_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprar',
            options={'ordering': ['-created'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
    ]
