# Generated by Django 3.1.3 on 2021-01-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comprar', '0005_auto_20210112_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprarimagenes',
            options={'verbose_name': 'Imagenes Compra'},
        ),
    ]
