# Generated by Django 3.1.3 on 2021-01-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo ')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Imagen')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('ambientes', models.IntegerField(verbose_name='Ambientes')),
                ('superficie', models.IntegerField(verbose_name='Superficie')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Editado')),
            ],
        ),
        migrations.CreateModel(
            name='AlquilarImagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Imagenes', verbose_name='Imagenes')),
                ('alquilar', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alquilar.alquilar')),
            ],
        ),
    ]
