# Generated by Django 3.1.3 on 2021-01-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alquilar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alquilar',
            options={'ordering': ['-created'], 'verbose_name': 'Alquiler', 'verbose_name_plural': 'Alquileres'},
        ),
        migrations.AlterModelOptions(
            name='alquilarimagenes',
            options={'verbose_name': 'Imagenes Alquiler'},
        ),
    ]
