# Generated by Django 3.1.3 on 2021-01-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimagenes',
            options={'verbose_name': 'Agregar nueva Imagen', 'verbose_name_plural': 'Agregar nuevas Imagenes'},
        ),
    ]
