# Generated by Django 3.1.3 on 2021-01-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_auto_20210113_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimagenes',
            options={'verbose_name': 'Imagenes Venta '},
        ),
    ]
