# Generated by Django 3.1.3 on 2021-01-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_auto_20210122_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='superficie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Superficie'),
        ),
    ]
