# Generated by Django 3.1.3 on 2021-01-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_auto_20210113_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimagenes',
            options={'verbose_name': 'Agregar mas Imagenes  '},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='Ventas', verbose_name='Imagen'),
        ),
    ]
