# Generated by Django 3.1.3 on 2021-01-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_auto_20210113_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='imagen',
        ),
    ]
