# Generated by Django 3.1.3 on 2021-06-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_auto_20210228_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='moneda',
            field=models.CharField(choices=[('U$S', 'U$S'), ('$', '$')], default='$', max_length=100),
        ),
        migrations.AlterField(
            model_name='postimagenes',
            name='image',
            field=models.ImageField(upload_to='Ventas', verbose_name='Imagenes'),
        ),
    ]
