# Generated by Django 3.1.3 on 2021-01-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0005_auto_20210114_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'Publicacion', 'verbose_name_plural': 'Publicaciones'},
        ),
    ]
