# Generated by Django 3.1.3 on 2021-01-13 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Editado')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PostAlquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo ')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, upload_to='Ventas', verbose_name='Imagen')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('ambientes', models.IntegerField(verbose_name='Ambientes')),
                ('superficie', models.IntegerField(verbose_name='Superficie')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('autores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categories', models.ManyToManyField(to='Alquileres.Category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PostImagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Imagenes', verbose_name='Imagenes')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alquileres.postalquiler')),
            ],
            options={
                'verbose_name': 'Agregar mas Imagenes  ',
            },
        ),
    ]
