# Generated by Django 3.1.3 on 2021-02-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquileres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalquiler',
            name='content',
            field=models.TextField(max_length=800, verbose_name='Contenido'),
        ),
    ]
