# Generated by Django 3.1.3 on 2021-01-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alquileres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimagenes',
            options={'verbose_name': 'Agregar mas Imagenes'},
        ),
        migrations.RenameField(
            model_name='postalquiler',
            old_name='image',
            new_name='imagen',
        ),
    ]
