# Generated by Django 3.1.3 on 2021-01-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alquileres', '0002_auto_20210113_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postalquiler',
            options={'ordering': ['-created'], 'verbose_name': 'Publicacion', 'verbose_name_plural': 'Plublicaciones'},
        ),
    ]
