# Generated by Django 3.1.3 on 2021-01-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquileres', '0003_auto_20210122_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalquiler',
            name='superficie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Superficie (locales u oficinas)'),
        ),
    ]
