# Generated by Django 3.1.3 on 2021-01-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alquileres', '0003_auto_20210117_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimagenes',
            options={'verbose_name': 'Imagenes de Publicacion '},
        ),
    ]
