# Generated by Django 3.1.3 on 2021-01-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alquileres', '0004_auto_20210120_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimagenes',
            options={'verbose_name': 'Imagen de Publicacion', 'verbose_name_plural': 'Imagenes de Publicacion'},
        ),
    ]
