# Generated by Django 3.1.3 on 2021-02-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquileres', '0004_auto_20210122_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalquiler',
            name='content',
            field=models.TextField(max_length=400, verbose_name='Contenido'),
        ),
    ]
