# Generated by Django 3.1.3 on 2021-02-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquileres', '0004_auto_20210227_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalquiler',
            name='frente',
            field=models.CharField(blank=True, choices=[('Externo', 'Externo'), ('Contrafrente', 'Contrafrente')], default='Externo', max_length=100, null=True),
        ),
    ]
