# Generated by Django 3.1.3 on 2021-01-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquileres', '0005_auto_20210120_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimagenes',
            options={},
        ),
        migrations.AlterField(
            model_name='postalquiler',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Ventas', verbose_name='Imagen'),
        ),
    ]
