# Generated by Django 3.1.3 on 2021-06-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquileres', '0006_auto_20210227_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimagenes',
            name='image',
            field=models.ImageField(upload_to='Alquileres', verbose_name='Imagenes'),
        ),
    ]
