# Generated by Django 3.2.5 on 2021-07-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquileres', '0007_auto_20210625_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalquiler',
            name='balcon',
            field=models.CharField(blank=True, choices=[('Con Balcon', 'Con Balcon'), ('Sin Balcon', 'Sin Balcon')], default='Con Balcon', max_length=100, null=True),
        ),
    ]
