# Generated by Django 3.1.3 on 2021-01-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alquileres', '0008_auto_20210120_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postalquiler',
            old_name='superficie',
            new_name='baños',
        ),
    ]
