# Generated by Django 3.1.3 on 2021-01-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquileres', '0009_auto_20210120_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalquiler',
            name='baños',
            field=models.IntegerField(verbose_name='Baños'),
        ),
    ]
