# Generated by Django 3.1.3 on 2021-01-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquileres', '0010_auto_20210120_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postalquiler',
            name='ambientes',
        ),
        migrations.AddField(
            model_name='postalquiler',
            name='dormitorios',
            field=models.IntegerField(default=None, verbose_name='Dormitorios'),
        ),
    ]
